//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DBFR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int idFactura { get; set; }
        public int numero_factura { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public decimal totalFactura { get; set; }
        public Nullable<int> idReserva_id { get; set; }
        public object IdReserva_id { get; internal set; }
        public virtual Reserva Reserva { get; set; }
    }
}
