//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturaEmitida
    {
        public int id_factura { get; set; }
        public int id_reserva { get; set; }
        public string nif_facturaEmitida { get; set; }
        public Nullable<double> import_base { get; set; }
        public Nullable<double> import_liquido { get; set; }
        public Nullable<double> iva_factura { get; set; }
        public string nombreLegal { get; set; }
        public Nullable<System.DateTime> fecha_facturaEmitida { get; set; }
        public string comentari_facturaEmitida { get; set; }
    
        public virtual reserva reserva { get; set; }
    }
}
