//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitacion
    {
        public int id_habitacion { get; set; }
        public Nullable<int> numero_habitacion { get; set; }
        public Nullable<int> id_tipo_habitacion { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<double> precio_habitacion { get; set; }
        public Nullable<bool> discapacidad_habitacion { get; set; }
    
        public virtual estado_habitacion estado_habitacion { get; set; }
        public virtual tipo_habitacion tipo_habitacion { get; set; }
    }
}
