//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historico
    {
        public int id_reserva { get; set; }
        public int id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string metodo_pago { get; set; }
        public Nullable<int> num_personas { get; set; }
        public Nullable<int> iva { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> sw_factura { get; set; }
        public Nullable<double> total_precio { get; set; }
    
        public virtual reserva reserva { get; set; }
    }
}
