//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSOL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelSOLEntities2 : DbContext
    {
        public HotelSOLEntities2()
            : base("name=HotelSOLEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<estado_habitacion> estado_habitacion { get; set; }
        public virtual DbSet<facturaEmitida> facturaEmitida { get; set; }
        public virtual DbSet<habitacion> habitacion { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<reserva_servicioExtra> reserva_servicioExtra { get; set; }
        public virtual DbSet<servicioExtra> servicioExtra { get; set; }
        public virtual DbSet<servicioReestauranteOtros> servicioReestauranteOtros { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<temporada> temporada { get; set; }
        public virtual DbSet<tipo_habitacion> tipo_habitacion { get; set; }
        public virtual DbSet<tipoPension> tipoPension { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<historico> historico { get; set; }
        public virtual DbSet<login_test> login_test { get; set; }
    }
}
