//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserva()
        {
            this.facturaEmitida = new HashSet<facturaEmitida>();
            this.historico = new HashSet<historico>();
            this.reserva_servicioExtra = new HashSet<reserva_servicioExtra>();
        }
    
        public int id_reserva { get; set; }
        public int id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> id_temporada { get; set; }
        public string metodo_pago { get; set; }
        public Nullable<int> num_personas { get; set; }
        public Nullable<bool> discapacidad { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> sw_factura { get; set; }
        public Nullable<int> id_pension { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual cliente cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaEmitida> facturaEmitida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historico> historico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva_servicioExtra> reserva_servicioExtra { get; set; }
        public virtual temporada temporada { get; set; }
        public virtual tipoPension tipoPension { get; set; }
    }
}
