//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicioReestauranteOtros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servicioReestauranteOtros()
        {
            this.reserva_servicioExtra = new HashSet<reserva_servicioExtra>();
        }
    
        public int id_servicio { get; set; }
        public Nullable<int> id_reserva { get; set; }
        public string nombre_servicio { get; set; }
        public Nullable<double> precio_servicio { get; set; }
        public string comentario_servicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva_servicioExtra> reserva_servicioExtra { get; set; }
    }
}
