//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string apellido1_usuario { get; set; }
        public string apellido2_usuario { get; set; }
        public System.DateTime fecha_alta_usuario { get; set; }
        public Nullable<System.DateTime> fecha_baja_usuario { get; set; }
        public Nullable<System.DateTime> fecha_ultima_conexion_usuario { get; set; }
        public int permisos_usuario { get; set; }
    }
}
